### ISSUE TITLE
problem with lxml on OS X

### ISSUE THREAD

**Issue by fulv** [gisweb/gisweb.iol#1]
Could you please find out which versions of libxml2 and libsxlt are used to compile lxml on your working instance?

I managed to figure out how to link to any specific version of libxml2, and somewhere on SO it seemed like I needed 2.7.8, but it's still not working:

```
>>> from lxml import etree
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/fulvio/plone/gisweb/lib/python2.7/site-packages/lxml/etree.so, 2): Symbol not found: _xmlBufContent
  Referenced from: /Users/fulvio/plone/gisweb/lib/python2.7/site-packages/lxml/etree.so
  Expected in: flat namespace
 in /Users/fulvio/plone/gisweb/lib/python2.7/site-packages/lxml/etree.so

**Comment by brenokcc** [comment]
Thanks!!!
That worked nicely.
